[package]
name = "robot-rename"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = "0.5.0"
eframe = "0.23.0"
egui = "0.23.0"
url = "2.4.1"
url_open = "0.0.2"
